# Deploys bucket for docs infra

# Cloudfront and s3 bucket

Parameters:
  Env:
    Description: Environment deploy to
    Type: String

Conditions:
  IsPrd: !Equals
    - !Ref Env
    - prd


Resources:
  # ---------------------------------------------------------------------------
  # Bucket
  # Create bucket static site logs
  # ---------------------------------------------------------------------------
  S3BucketLogs:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      # BucketName: 'cw-east-dev-bucket-web-logs'
      BucketName: !Sub 'cw-east-${Env}-bucket-web-logs'
      LifecycleConfiguration:
        Rules:
          - Id: AbortIncompleteMultipartUploadAfter1Day
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
          - Id: TransitionWithAge
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
              - StorageClass: GLACIER
                TransitionInDays: 365
      Tags:
        - Key: app:name
          Value: cloudwege-docs
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE


  # ---------------------------------------------------------------------------
  # Bucket
  # Create bucket static site static files
  # ---------------------------------------------------------------------------
  S3BucketRoot:
    Type: AWS::S3::Bucket
    Properties:
      # AccelerateConfiguration:
      #   AccelerateConfiguration
      # AccessControl: LogDeliveryWrite
      # AnalyticsConfigurations:
      #   - AnalyticsConfiguration
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub 'cw-east-${Env}-bucket-web-root'
      # CorsConfiguration:
      #   CorsConfiguration
      # InventoryConfigurations:
      #   - InventoryConfiguration
      LoggingConfiguration:
        DestinationBucketName:
          Ref: S3BucketLogs
        LogFilePrefix: origin/
      # MetricsConfigurations:
      #   - MetricsConfiguration
      # NotificationConfiguration:
      #   NotificationConfiguration
      # ObjectLockConfiguration:
      #   ObjectLockConfiguration
      # ObjectLockEnabled: Boolean
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
      Tags:
        - Key: app:name
          Value: cloudwege-docs
      # VersioningConfiguration:
      #   VersioningConfiguration
      # WebsiteConfiguration:
      #   WebsiteConfiguration

  # ---------------------------------------------------------------------------
  # Cloudfront origin identity
  # Create bucket static site static files
  # ---------------------------------------------------------------------------
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: CloudFront OAI for cloudwedge.io


  # ---------------------------------------------------------------------------
  # CloudFront Distribution
  # Distro in front of the s3 static bucket
  # ---------------------------------------------------------------------------
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Condition: IsPrd
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub '${Env}.cloudwedge.io'
        CustomErrorResponses:
          - ErrorCachingMinTTL: 60
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 60
            ErrorCode: 403
            ResponseCode: 403
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          Compress: true
          DefaultTTL: 60
          ForwardedValues:
            QueryString: true
          MaxTTL: 60
          TargetOriginId:
            Fn::Sub: S3-${AWS::StackName}-root
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        DefaultRootObject: index.html
        IPV6Enabled: true
        Logging:
          Bucket: !GetAtt S3BucketLogs.DomainName
          IncludeCookies: false
          Prefix: cdn/
        Origins:
        - DomainName: !GetAtt S3BucketRoot.DomainName
          Id:
            Fn::Sub: S3-${AWS::StackName}-root
          S3OriginConfig:
            OriginAccessIdentity:
              Fn::Join:
              - ''
              - - origin-access-identity/cloudfront/
                - Ref: CloudFrontOriginAccessIdentity
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Sub 'arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/0e423b65-a19f-4439-ae5b-e7ed69302405'
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: sni-only
      Tags:
        - Key: app:name
          Value: cloudwege-docs


  # ---------------------------------------------------------------------------
  # Bucket Policy
  # Create bucket static site static files
  # ---------------------------------------------------------------------------
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: S3BucketRoot
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Resource: !Sub "${S3BucketRoot.Arn}/*"
          Principal:
            CanonicalUser:
              Fn::GetAtt:
              - CloudFrontOriginAccessIdentity
              - S3CanonicalUserId