name: dev release

on:
  push:
    branches:
      - develop
    paths-ignore:
      - "**/README.md"
      - "**/dox/**"
      - "**/admin/**"

env:
  TARGET_ENV: dev

jobs:
  releaseDocs:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install
        run: |
          npm install

      # - name: Deploy Infra
      #   run: |
      #     npm run docs:infra

      - name: Sync Site
        run: |
          npm run docs:sync
